/* 대입설명회 UI kit — 샘플 데이터 */
window.DSR_DATA = {
  sessions: [
    {
      id: 'ku',
      university: '한국대학교',
      title: '2027학년도 수시 입학설명회',
      types: ['수시', '학생부종합'],
      date: '7월 24일 (금)',
      time: '14:00',
      place: '서울 · 대강당',
      region: '서울',
      seatsLeft: 38,
      seatsTotal: 300,
      desc: '2027학년도 수시 전형의 주요 변경 사항과 학생부종합전형 평가 기준을 입학사정관이 직접 안내합니다. 설명회 후 단과대학별 개별 상담 부스가 운영됩니다.',
      rounds: [
        { id: 'r1', label: '1회차', time: '10:00', left: 0, total: 300 },
        { id: 'r2', label: '2회차', time: '14:00', left: 38, total: 300 },
        { id: 'r3', label: '3회차', time: '17:00', left: 121, total: 300 },
      ],
    },
    {
      id: 'mirim',
      university: '미림대학교',
      title: '정시 전형 안내 및 입시 Q&A',
      types: ['정시'],
      date: '8월 2일 (일)',
      time: '10:00',
      place: '온라인 생중계',
      region: '온라인',
      seatsLeft: 512,
      seatsTotal: 1000,
      desc: '정시 전형 지원 전략과 최근 3개년 입시 결과를 공개합니다. 실시간 채팅으로 질문을 받아요.',
      rounds: [
        { id: 'r1', label: '1회차', time: '10:00', left: 512, total: 1000 },
        { id: 'r2', label: '2회차', time: '15:00', left: 866, total: 1000 },
      ],
    },
    {
      id: 'hanbit',
      university: '한빛대학교',
      title: '논술전형 대비 특강 · 기출 해설',
      types: ['논술', '수시'],
      date: '8월 9일 (일)',
      time: '13:00',
      place: '대전 · 국제회의실',
      region: '대전',
      seatsLeft: 14,
      seatsTotal: 180,
      desc: '최근 3개년 논술 기출을 출제위원 관점에서 해설합니다. 계열별(인문/자연) 분반으로 진행돼요.',
      rounds: [
        { id: 'r1', label: '인문계열', time: '13:00', left: 14, total: 180 },
        { id: 'r2', label: '자연계열', time: '16:00', left: 27, total: 180 },
      ],
    },
    {
      id: 'sejong',
      university: '세종과학대학교',
      title: '첨단학과 신설 안내 · 캠퍼스 투어',
      types: ['수시', '정시'],
      date: '8월 16일 (일)',
      time: '11:00',
      place: '세종 · 본관 로비 집결',
      region: '세종',
      seatsLeft: 96,
      seatsTotal: 120,
      desc: '반도체·AI 신설 학과 소개와 함께 재학생이 직접 안내하는 캠퍼스 투어가 포함된 설명회입니다.',
      rounds: [
        { id: 'r1', label: '오전', time: '11:00', left: 96, total: 120 },
        { id: 'r2', label: '오후', time: '14:30', left: 44, total: 120 },
      ],
    },
    {
      id: 'gaon',
      university: '가온대학교',
      title: '학부모 대상 입시 로드맵 설명회',
      types: ['수시'],
      date: '8월 23일 (일)',
      time: '10:30',
      place: '부산 · 컨벤션홀',
      region: '부산',
      seatsLeft: 0,
      seatsTotal: 250,
      closed: true,
      desc: '고1·2 학부모를 위한 장기 입시 전략. 이번 회차는 마감되었어요.',
      rounds: [{ id: 'r1', label: '단일 회차', time: '10:30', left: 0, total: 250 }],
    },
    {
      id: 'dasan',
      university: '다산대학교',
      title: '교사 초청 전형 설명회',
      types: ['수시', '정시'],
      date: '8월 30일 (일)',
      time: '15:00',
      place: '서울 · 교육관 201호',
      region: '서울',
      seatsLeft: 61,
      seatsTotal: 80,
      desc: '진학지도 교사를 위한 심화 세션. 전형별 평가 루브릭과 학교생활기록부 반영 방식을 다룹니다.',
      rounds: [{ id: 'r1', label: '단일 회차', time: '15:00', left: 61, total: 80 }],
    },
  ],
  myReservations: [
    { sessionId: 'ku', round: '2회차 · 14:00', code: 'KU-0724-0138', name: '김수민', status: 'confirmed', seat: '나열 7번' },
    { sessionId: 'hanbit', round: '인문계열 · 13:00', code: 'HB-0809-0042', name: '김수민', status: 'waiting', seat: '대기 3번' },
  ],
  pastReservations: [
    { university: '미림대학교', title: '전공 탐색 오픈캠퍼스', date: '5월 31일', status: 'done' },
    { university: '한국대학교', title: '고3 대상 모의 면접 특강', date: '4월 12일', status: 'done' },
  ],
};
